#!/bin/sh

set -eu

namespace=SDL3/

if [ -z "${HOME-}" ] || ! [ -w "${HOME}" ]; then
    export HOME="${AUTOPKGTEST_TMP}"
fi

export SDL_AUDIO_DRIVER=dummy
export SDL_VIDEO_DRIVER=dummy
cd "$AUTOPKGTEST_TMP"

if [ -z "$(ginsttest-runner -l "$namespace")" ]; then
    echo "Error: no installed-tests found matching $namespace" >&2
    exit 1
fi

exec ginsttest-runner --tap "$namespace"
